### ISSUE TITLE
ONNX: export failure: Unsupported: ONNX export of operator adaptive pooling

### ISSUE THREAD

**Issue by haheheixi** [Arrowes/FEY-YOLOv7#1]
Thank you for your work. I encountered an error while trying to convert best.pt to ONNX. How can I resolve it?

`ONNX: export failure: Unsupported: ONNX export of operator adaptive pooling, since output_size is not constant.. Please feel free to request support or submit a pull request on PyTorch GitHub.
`

**Comment by haheheixi** [comment]
Updating to torch version 2.2.2 resolved this issue.

**Comment by liyothrin** [comment]
> 谢谢你的工作。尝试将 best.pt 转换为ONNX时遇到错误。我该如何解决？
> 
> `ONNX: export failure: Unsupported: ONNX export of operator adaptive pooling, since output_size is not constant.. Please feel free to request support or submit a pull request on PyTorch GitHub. `

Hello,I want to know where is data?How to run?Can you tell me?Thank you very much

**Comment by haheheixi** [comment]
`python3.8 detect.py --weights ./best.pt  --source mydata/test/1.png --data data/coco.yaml`
This way works. the --data parameter has no effect.

**Comment by liyothrin** [comment]
> `python3.8 detect.py --weights ./best.pt --source mydata/test/1.png --data data/coco.yaml` This way works. the --data parameter has no effect.

sorry,I  still don't quite understand what you mean,"We have looked through the code content and did not find any specific code related to fatigue driving. We are not sure where the dataset is. Could you please confirm if you have run it?"

**Comment by liyothrin** [comment]
> `python3.8 detect.py --weights ./best.pt --source mydata/test/1.png --data data/coco.yaml` This way works. the --data parameter has no effect.

thank you very much. I have runned.
