### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by CedricYcz** [Arrowes/FEY-YOLOv7#2]
mydata\Fatigue0\data.yaml数据集在哪里可以得到呀

**Comment by Arrowes** [comment]
抱歉，该数据集属于学校资产，无法公开

**Comment by CedricYcz** [comment]
好的，麻烦了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月30日 14:58 |
| 收件人 | Arrowes/FEY-YOLOv7 ***@***.***> |
| 抄送人 | zheyangba ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Arrowes/FEY-YOLOv7] 数据集 (Issue #2) |

抱歉，该数据集属于学校资产，无法公开
