### ISSUE TITLE
No mydata\Fatigue0\data.yaml

### ISSUE THREAD

**Issue by SetonLiang** [Arrowes/FEY-YOLOv7#4]
mydata\Fatigue文件夹下面没有data.yaml

**Comment by SetonLiang** [comment]
> mydata\Fatigue文件夹下面没有data.yaml

![image](https://github.com/user-attachments/assets/1c4d54c8-1c80-49a8-8c38-0a66c70711dd)

**Comment by Arrowes** [comment]
这个数据集不公开，可以用自制数据集，data.yaml格式可参考yolov5
